In [1]:
from spending_tracker.database import supabase_client
from spending_tracker.database import transactions
from spending_tracker.data_ingestion import csv_parsing
from pathlib import Path

In [2]:
db_client = supabase_client.load_supabase_client()

In [3]:
processed_transactions_data_home = Path().resolve().parent / "data" / "transactions" / "processed"
transaction_metadata_home = Path().resolve().parent / "data" / "transactions_metadata"
print(processed_transactions_data_home)

specific_month = "August-26"

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed

In [4]:
transactions_df = csv_parsing.load_csv_in_batch(processed_transactions_data_home,
                                                specific_month=specific_month,
                                                dtype_kwargs={
                                                    "account_id": str,
                                                })

transactions_metadata_df = csv_parsing.load_csv_in_batch(transaction_metadata_home,
                                                         specific_month=specific_month,
                                                         dtype_kwargs={
                                                             "account_id": str,
                                                         })

[PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Joint/Nationwide/03076275/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Joint/Nationwide/03076275/July-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Amex/51016/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Amex/51016/July-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Nationwide/34490057/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Nationwide/34490057/July-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Amex/52006/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Amex/52006/July-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/33053200/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/33053200/July-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/69448147/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/69448147/July-26/transactions.csv')]
[PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Joint/Nationwide/03076275/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Amex/51016/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Radhika/Nationwide/34490057/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Amex/52006/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/33053200/August-26/transactions.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed/Taj/Chase/69448147/August-26/transactions.csv')]
[PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Joint/Nationwide/03076275/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Joint/Nationwide/03076275/July-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Amex/51016/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Amex/51016/July-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Nationwide/34490057/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Nationwide/34490057/July-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Amex/52006/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Amex/52006/July-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/33053200/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/33053200/July-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/69448147/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/69448147/July-26/transaction_metadata.csv')]
[PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Joint/Nationwide/03076275/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Amex/51016/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Radhika/Nationwide/34490057/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Amex/52006/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/33053200/August-26/transaction_metadata.csv'), PosixPath('/Users/taj/Documents/Spending-Tracker-Agent/data/transactions_metadata/Taj/Chase/69448147/August-26/transaction_metadata.csv')]

In [5]:
transactions_df.head(10)

,event_id,date,month,account_id,user,bank,merchant,other_details,type,amount
0,364e7e1a6abe4ec7fc572c27d15617d7ef162a5c1a2977...,2026-08-03,August-26,03076275,Joint,Nationwide,AMAZON* 7L9H654J5 LONDON GB 4971,NaN,NaN,-7.99
1,17768a21ea083394a4a74379f320725988dadacbfd20ea...,2026-08-03,August-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-14.39
2,1889355b6fa062596fef6087a8747405bcf92556c2bee3...,2026-08-04,August-26,03076275,Joint,Nationwide,Vue Cinemas Harrow GB,APPLEPAY 9160,NaN,-12.61
3,597c58ee6ca7bfbfc49ca9f29961a997453da263c09cf2...,2026-08-04,August-26,03076275,Joint,Nationwide,Vue Entertainment Ltd London GB,APPLEPAY 5176,NaN,-15.00
4,fcc181b6a2d75ee0c81e6786e95538f4a20d315af70eb1...,2026-08-04,August-26,03076275,Joint,Nationwide,ELLO GROUP / VUE PASS HUDDERSFIELD GB,APPLEPAY 5176,NaN,-15.00
5,fd2c233185aaf22674a53fc4a743843ffdd1a889328d94...,2026-08-04,August-26,03076275,Joint,Nationwide,SP DUSK.COM LEEDS GB,APPLEPAY 5176,NaN,-114.99
6,936b470494bffd5317a6a6855cdefb7b78e4e6bccf5bef...,2026-08-05,August-26,03076275,Joint,Nationwide,SimSim Bakery and Restura London GB,APPLEPAY 4914,NaN,-5.50
7,6247f60f839bfa5e834a0cfbc7a883961577f3c52244ad...,2026-08-05,August-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-6.14
8,1a52fae91715b84bac9885b579c4025008b8a65c66ba1c...,2026-08-08,August-26,03076275,Joint,Nationwide,ZETTLE_*BASTANI LONDON LONDON GB,APPLEPAY 9160,NaN,-9.90
9,c330356bf39788e3667e4182cb674cee7e2787baafdf99...,2026-08-08,August-26,03076275,Joint,Nationwide,Kingsfield Arms Harrow GB,APPLEPAY 9160,NaN,-27.13

In [6]:
transactions_metadata_df.head()

,event_id,llm_merchant,llm_category,manual_merchant,manual_category,manual_amount,hidden
0,364e7e1a6abe4ec7fc572c27d15617d7ef162a5c1a2977...,Amazon,shopping,NaN,NaN,NaN,False
1,17768a21ea083394a4a74379f320725988dadacbfd20ea...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,False
2,1889355b6fa062596fef6087a8747405bcf92556c2bee3...,Vue Cinemas Harrow,dining,NaN,NaN,NaN,False
3,597c58ee6ca7bfbfc49ca9f29961a997453da263c09cf2...,Vue Entertainment Ltd,dining,NaN,NaN,NaN,False
4,fcc181b6a2d75ee0c81e6786e95538f4a20d315af70eb1...,Vue,dining,NaN,NaN,NaN,False

In [7]:
transactions_df.shape

(136, 10)

In [8]:
transactions_metadata_df.shape

(136, 7)

In [9]:
transactions.upload_transactions_to_db(transactions_df, 
                                       db_client, 
                                       table_name="transactions")

APIResponse(data=[{'event_id': '364e7e1a6abe4ec7fc572c27d15617d7ef162a5c1a2977d72ba98252301917b3', 'date': '2026-08-03', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'AMAZON* 7L9H654J5 LONDON GB 4971', 'other_details': None, 'type': None, 'amount': -7.99, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '17768a21ea083394a4a74379f320725988dadacbfd20eaa03dbb349bb35ed687', 'date': '2026-08-03', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -14.39, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '1889355b6fa062596fef6087a8747405bcf92556c2bee36a980d9586a4fe53c1', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Vue Cinemas Harrow GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -12.61, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '597c58ee6ca7bfbfc49ca9f29961a997453da263c09cf2618131ce66accdb948', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Vue Entertainment Ltd London GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -15, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'fcc181b6a2d75ee0c81e6786e95538f4a20d315af70eb164b68136457389cdf6', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'ELLO GROUP / VUE PASS HUDDERSFIELD GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -15, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'fd2c233185aaf22674a53fc4a743843ffdd1a889328d94909cdf139a9da8e9d4', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SP DUSK.COM LEEDS GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -114.99, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '936b470494bffd5317a6a6855cdefb7b78e4e6bccf5bef5590a0e4f7788abb00', 'date': '2026-08-05', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SimSim Bakery and Restura London GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -5.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '6247f60f839bfa5e834a0cfbc7a883961577f3c52244ada3d42a41d83e06d46d', 'date': '2026-08-05', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -6.14, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '1a52fae91715b84bac9885b579c4025008b8a65c66ba1ca35fb56db8dbe88ef9', 'date': '2026-08-08', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'ZETTLE_*BASTANI LONDON LONDON GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -9.9, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'c330356bf39788e3667e4182cb674cee7e2787baafdf99be6c7d25cf07a3183f', 'date': '2026-08-08', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Kingsfield Arms Harrow GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -27.13, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '058125eeacc40a15c5db99b445300b3f3f7accbaeaaf5cdd60b651732db61383', 'date': '2026-08-08', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Kingsfield Arms Harrow GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -27.13, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '8de9c1be2fc74238e7c4c4440869aa6156787c4f56cb87b4b93640ecfe7cc571', 'date': '2026-08-10', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -4.34, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'ffc0e867ed0749405a25667c2515f8e45380188e65216e6c0fd6f40936dd0e2f', 'date': '2026-08-10', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TST-MEAA London London GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -60.86, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '894a32501d20c12794d1781a4952aea914c66feadcc156c36c5e0396b30b86f8', 'date': '2026-08-10', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'BATTLEKART ST ALBANS L ST ALBANS GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -180, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'bc6993037e27c67fc626a3d1316e409c8129b59fe5343e067ee44e43ea8fe3bd', 'date': '2026-08-10', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SQ *JAPES ST ALBANS St. Albans GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -45.92, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '0c67a87bc1ded6d17a33e1c207855efe9f237675b81d5b18b226b4c2189c458d', 'date': '2026-08-11', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -0.89, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '80d268c2b7fc73d4256d78ec22a8568411d608f0153e03cf103a68701566b89d', 'date': '2026-08-11', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -12.55, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '72ce957ad4be3ef47fd3ed63fb367a4edc885caf1662ec2a88cb00058fc7fc5b', 'date': '2026-08-11', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Costcutter London GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -8.77, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '6b93fe162b7a212940ff79bb5632fceec40bb990a742143f8cde8cc78bf94321', 'date': '2026-08-12', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'WEMBLEY PARK LONDON GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -3.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '12e992f6185851e5c3485b43f7b7f081cd737965d30bafe1c23181806a29cda9', 'date': '2026-08-12', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -5.2, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'a5b0395c6065403e16778b95cdb7ca65d703a2b55acaa8e9e1b7d963a1e9f6d5', 'date': '2026-08-12', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SumUp *ASHVINI CASH A Harrow GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -10.98, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '022c47f8d17b60285684c3e6eec99b01b72b91637fd7b4d95f2ed1b05b74d763', 'date': '2026-08-12', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'LS Afrikana Wembley London GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -57.15, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '94d9335fb249ab895474f39433095b79caa04207fdf5061f88060c4cb2c66987', 'date': '2026-08-15', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -3, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'd4912b743e8408a53796ee8eb3fd9e512e573cfa5718e55d021793664869bc81', 'date': '2026-08-17', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'LIDL GB SOUTH RUISLIP LIDL GB SOUTH GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -2.18, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '543a86bbdea16f2331a2268065fa10c7f8ffbc085b76c9cc846ea6fd2c97e2cb', 'date': '2026-08-18', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -4.78, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '861d4b714bba15715adc45d977fce0333990aefde2a6390c4e06e3fb7513e4e1', 'date': '2026-08-19', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SAIF PARVEZ', 'other_details': None, 'type': None, 'amount': -23, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '152475f6077f31322d6c4dd23ec16242a7e35dfb18fdb725a9857dfb7aa6f034', 'date': '2026-08-20', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS BOREHAMWOOD - 3 BOREHAMWOOD GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -7.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '597ba1763d56eddba758c2c4b8b081eb1ffcefae6ca876c46f4eb3d86e0de6fb', 'date': '2026-08-21', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TAJ PATEL', 'other_details': None, 'type': None, 'amount': 1400, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'b609a4494349c1b6afacab86ed759a9f0dd82a867f1b9ebd55570b99f91ca02e', 'date': '2026-08-21', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 21 August 2026', 'other_details': None, 'type': None, 'amount': -1250, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '958411bf072c62a3060ceb8fb6e5dc616a21c61030ea35ce5e7ed9e8dd103ee6', 'date': '2026-08-21', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -3.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '8c9ae41f08726f0aa947433d48d699e9748a1a27447a2c00baca962e5f493c45', 'date': '2026-08-24', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'AIRALO EDINBURGH GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '440f702438cf67f47ec3ac99518a1c153b489e491c56cc66516185bf45a52279', 'date': '2026-08-26', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'SACHIN PATEL', 'other_details': None, 'type': None, 'amount': -22.98, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'da07bdea79557a754bc2f1ea77c733bcade0e72f7b34c9ced09296febd84aef5', 'date': '2026-08-27', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Argos MILTON KEYNES GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -4.19, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'f347f70fdb3339ec12f6a687ad4dd32b07508427ebbaf98b650dc8b146eea6af', 'date': '2026-08-27', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -10.42, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '951b5a74a87a10ffb6a5a765cc4613563a3551e134d0414abf92d7a33ff10782', 'date': '2026-08-28', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '070436 34490057 Credit 28 August 2026', 'other_details': None, 'type': None, 'amount': 150, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '08ddec50a56c6aecbb9338f24f715dc636cea9bf14e4b500d801eb4640e4ccc4', 'date': '2026-08-31', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -6.89, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '710800763bffeb197fe88e72cb5c799f6b1453458cc24aa0166e4ec782aab92e', 'date': '2026-08-31', 'month': 'August-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -9.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '62bb42dac146220e7ba17aaeae7389d1cbf2deebaea848994826ffe94a282394', 'date': '2026-08-31', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TESCO PETROL 5288 5288T', 'other_details': 'STANMORE', 'type': None, 'amount': -1.4, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '7d4757f5ef9650f395b5f1a1f2f54caa44388f58abc2e43a354d1d6c87ba8693', 'date': '2026-08-29', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'FS002307 QUEENSBURY 731', 'other_details': 'Stanmore', 'type': None, 'amount': -62.36, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'f0973b66cbd0bdfd1ba72f3459cc0fb90eadc1034d9fdc8ad1df3ea5b6c3bd6e', 'date': '2026-08-29', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TFL TRAVEL CHARGE', 'other_details': 'TFL.GOV.UK/CP', 'type': None, 'amount': -7.2, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '9d059a77eb17b9b8e3dddad066016c4c5fd191dd3df55c2bb355651336c97725', 'date': '2026-08-28', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'GREGGS @ MFG QUEENSBURY', 'other_details': 'EDGWARE', 'type': None, 'amount': -1, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '177f09b05250b48f1830eb873ae2e7236fb8e17babe98e06a42216ff0f4d42c6', 'date': '2026-08-28', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'WM MORRISONS STORES - Q', 'other_details': 'LONDON', 'type': None, 'amount': -2.66, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '9a40ee70e7c229f702628ba2edc07079cc1dcab8cddea38659813b31648a58bd', 'date': '2026-08-19', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'WM MORRISONS STORES', 'other_details': 'BOREHAMWOOD', 'type': None, 'amount': -10.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '6d84c2a1c2789646225267a8fb0067fb6f91b324119a22fe98d7b67934cb7325', 'date': '2026-08-16', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'ETSY UK', 'other_details': 'LONDON', 'type': None, 'amount': -12.98, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '485ffdf469ada45ef91e3521843b6ad0eb6a02597e54c06245fa46edda261511', 'date': '2026-08-16', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TESCO PETROL 5288 5288T', 'other_details': 'STANMORE', 'type': None, 'amount': -1.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '51b1c76544a0d05dad20580fd10567949af77b57d0a7bc829974b90d83aba270', 'date': '2026-08-14', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'LONDON STANSTED AIRPORT', 'other_details': 'STANSTED', 'type': None, 'amount': -75.2, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '440c7b9f20c5df08fce75692859cdcf619922f0e28e3a444fdd459d71c4a5beb', 'date': '2026-08-13', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': '2725 - BOREHAMWOOD', 'other_details': 'HERTFORDSHIRE', 'type': None, 'amount': -3.18, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '2b90432e923bda87dd706b21d29e30c81c36b8f30bb4522ccc634f1a445b8822', 'date': '2026-08-13', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': '2725 - BOREHAMWOOD', 'other_details': 'HERTFORDSHIRE', 'type': None, 'amount': -4.49, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '0bdc52a673cecab46193b8091f7de0ae218432dec231c8f5fee14a04f3346795', 'date': '2026-08-12', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TESCO STORE 2126 2126TE', 'other_details': 'BOREHAMWOOD', 'type': None, 'amount': -12.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '012867e0f1c1f37a6fd6aa5d8bdee12c1b576d6728cf9751b8e61114286f08bb', 'date': '2026-08-11', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'FS2307 Queensbury 73156', 'other_details': 'Stanmore', 'type': None, 'amount': -64.76, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'dd77874add7da58ef0d01fd1ca9ea2da5f684a13afdaf533d24760623c5d8419', 'date': '2026-08-07', 'month': 'August-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'WM MORRISONS STORES - Q', 'other_details': 'LONDON', 'type': None, 'amount': -1.12, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '84dfbb18d9df37fa9d80c93f575b9ed69b45821e15834b55be390bf7bcb35ca0', 'date': '2026-08-01', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'APPLE.COM/BILL 08001076285 IE', 'other_details': None, 'type': None, 'amount': -6.99, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'bcc42b4f037cf68aab9ef2ca5d8857edabcd59cb58aa5a74806a79556d012fe2', 'date': '2026-08-03', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'O2', 'other_details': None, 'type': None, 'amount': -10.5, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '26cf81ab0b6763b45835180ec7fcf36a6fab1a87134a4e1d9f363981a85d5658', 'date': '2026-08-03', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'THE GYM LTD', 'other_details': None, 'type': None, 'amount': -18.99, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '9104568005ab2c9d81b96066745667a0a617bdcdd49c248aa77f5430d6700e08', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'Jinal Patel', 'other_details': None, 'type': None, 'amount': 150, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': 'a0463b5ecba02e0b2f534b51a3a96435700091c40746862e82151cc3190f9787', 'date': '2026-08-04', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 04 August 2026', 'other_details': None, 'type': None, 'amount': -150, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '160df8b9055811791bedb5416195539127fb99e585df443954261744b713ec7f', 'date': '2026-08-14', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'Cards Direct Borehamwood GB', 'other_details': 'APPLEPAY 6855', 'type': None, 'amount': -1.29, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}, {'event_id': '76fafdf286392b2260286914a0828c83421a557639531a1ed0e0401d786a496c', 'date': '2026-08-14', 'month': 'August-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': "Pepe's Peri Peri London GB", 'other_details': 'APPLEPAY 6855', 'type': None, 'amount': -17.09, 'updated_at': '2026-09-02T17:13:34.720002+00:00'}

In [10]:
transactions.upload_transactions_to_db(transactions_metadata_df, 
                                       db_client, 
                                       table_name="transactions_metadata", 
                                       exclude_columns=["manual_merchant", "manual_category", "manual_amount", "hidden"])

APIResponse(data=[{'event_id': '364e7e1a6abe4ec7fc572c27d15617d7ef162a5c1a2977d72ba98252301917b3', 'llm_merchant': 'Amazon', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '17768a21ea083394a4a74379f320725988dadacbfd20eaa03dbb349bb35ed687', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '1889355b6fa062596fef6087a8747405bcf92556c2bee36a980d9586a4fe53c1', 'llm_merchant': 'Vue Cinemas Harrow', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '597c58ee6ca7bfbfc49ca9f29961a997453da263c09cf2618131ce66accdb948', 'llm_merchant': 'Vue Entertainment Ltd', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'fcc181b6a2d75ee0c81e6786e95538f4a20d315af70eb164b68136457389cdf6', 'llm_merchant': 'Vue', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'fd2c233185aaf22674a53fc4a743843ffdd1a889328d94909cdf139a9da8e9d4', 'llm_merchant': 'SP DUSK.COM LEEDS GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '936b470494bffd5317a6a6855cdefb7b78e4e6bccf5bef5590a0e4f7788abb00', 'llm_merchant': 'SimSim Bakery and Restura', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '6247f60f839bfa5e834a0cfbc7a883961577f3c52244ada3d42a41d83e06d46d', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '1a52fae91715b84bac9885b579c4025008b8a65c66ba1ca35fb56db8dbe88ef9', 'llm_merchant': 'ZETTLE_*BASTANI LONDON LONDON GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'c330356bf39788e3667e4182cb674cee7e2787baafdf99be6c7d25cf07a3183f', 'llm_merchant': 'Kingsfield Arms', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '058125eeacc40a15c5db99b445300b3f3f7accbaeaaf5cdd60b651732db61383', 'llm_merchant': 'Kingsfield Arms', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '8de9c1be2fc74238e7c4c4440869aa6156787c4f56cb87b4b93640ecfe7cc571', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'ffc0e867ed0749405a25667c2515f8e45380188e65216e6c0fd6f40936dd0e2f', 'llm_merchant': 'TST-MEAA London', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '894a32501d20c12794d1781a4952aea914c66feadcc156c36c5e0396b30b86f8', 'llm_merchant': 'Battlekart', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'bc6993037e27c67fc626a3d1316e409c8129b59fe5343e067ee44e43ea8fe3bd', 'llm_merchant': 'SQ *JAPES ST ALBANS St. Albans GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '0c67a87bc1ded6d17a33e1c207855efe9f237675b81d5b18b226b4c2189c458d', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '80d268c2b7fc73d4256d78ec22a8568411d608f0153e03cf103a68701566b89d', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '72ce957ad4be3ef47fd3ed63fb367a4edc885caf1662ec2a88cb00058fc7fc5b', 'llm_merchant': 'Costcutter', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '6b93fe162b7a212940ff79bb5632fceec40bb990a742143f8cde8cc78bf94321', 'llm_merchant': 'Wembley Park', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '12e992f6185851e5c3485b43f7b7f081cd737965d30bafe1c23181806a29cda9', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'a5b0395c6065403e16778b95cdb7ca65d703a2b55acaa8e9e1b7d963a1e9f6d5', 'llm_merchant': 'SumUp', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '022c47f8d17b60285684c3e6eec99b01b72b91637fd7b4d95f2ed1b05b74d763', 'llm_merchant': 'LS Afrikana', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '94d9335fb249ab895474f39433095b79caa04207fdf5061f88060c4cb2c66987', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'd4912b743e8408a53796ee8eb3fd9e512e573cfa5718e55d021793664869bc81', 'llm_merchant': 'Lidl', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '543a86bbdea16f2331a2268065fa10c7f8ffbc085b76c9cc846ea6fd2c97e2cb', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '861d4b714bba15715adc45d977fce0333990aefde2a6390c4e06e3fb7513e4e1', 'llm_merchant': 'SAIF PARVEZ', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '152475f6077f31322d6c4dd23ec16242a7e35dfb18fdb725a9857dfb7aa6f034', 'llm_merchant': 'Morrisons', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '597ba1763d56eddba758c2c4b8b081eb1ffcefae6ca876c46f4eb3d86e0de6fb', 'llm_merchant': 'TAJ PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'b609a4494349c1b6afacab86ed759a9f0dd82a867f1b9ebd55570b99f91ca02e', 'llm_merchant': '071490 77608825 Withdrawal', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '958411bf072c62a3060ceb8fb6e5dc616a21c61030ea35ce5e7ed9e8dd103ee6', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '8c9ae41f08726f0aa947433d48d699e9748a1a27447a2c00baca962e5f493c45', 'llm_merchant': 'Airaloo', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '440f702438cf67f47ec3ac99518a1c153b489e491c56cc66516185bf45a52279', 'llm_merchant': 'SACHIN PATEL', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'da07bdea79557a754bc2f1ea77c733bcade0e72f7b34c9ced09296febd84aef5', 'llm_merchant': 'Argos', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'f347f70fdb3339ec12f6a687ad4dd32b07508427ebbaf98b650dc8b146eea6af', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '951b5a74a87a10ffb6a5a765cc4613563a3551e134d0414abf92d7a33ff10782', 'llm_merchant': '070436 34490057 Credit', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '08ddec50a56c6aecbb9338f24f715dc636cea9bf14e4b500d801eb4640e4ccc4', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '710800763bffeb197fe88e72cb5c799f6b1453458cc24aa0166e4ec782aab92e', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '62bb42dac146220e7ba17aaeae7389d1cbf2deebaea848994826ffe94a282394', 'llm_merchant': 'TESCO PETROL 5288 5288T', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '7d4757f5ef9650f395b5f1a1f2f54caa44388f58abc2e43a354d1d6c87ba8693', 'llm_merchant': 'FS2307 Queensbury 73156', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'f0973b66cbd0bdfd1ba72f3459cc0fb90eadc1034d9fdc8ad1df3ea5b6c3bd6e', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '9d059a77eb17b9b8e3dddad066016c4c5fd191dd3df55c2bb355651336c97725', 'llm_merchant': 'Greggs', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '177f09b05250b48f1830eb873ae2e7236fb8e17babe98e06a42216ff0f4d42c6', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '9a40ee70e7c229f702628ba2edc07079cc1dcab8cddea38659813b31648a58bd', 'llm_merchant': 'Morrisons', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '6d84c2a1c2789646225267a8fb0067fb6f91b324119a22fe98d7b67934cb7325', 'llm_merchant': 'Etsy', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '485ffdf469ada45ef91e3521843b6ad0eb6a02597e54c06245fa46edda261511', 'llm_merchant': 'TESCO PETROL 5288 5288T', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '51b1c76544a0d05dad20580fd10567949af77b57d0a7bc829974b90d83aba270', 'llm_merchant': 'London Stansted Airport', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '440c7b9f20c5df08fce75692859cdcf619922f0e28e3a444fdd459d71c4a5beb', 'llm_merchant': '2725 - BOREHAMWOOD', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '2b90432e923bda87dd706b21d29e30c81c36b8f30bb4522ccc634f1a445b8822', 'llm_merchant': '2725 - BOREHAMWOOD', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '0bdc52a673cecab46193b8091f7de0ae218432dec231c8f5fee14a04f3346795', 'llm_merchant': 'TESCO STORE 2126 2126TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '012867e0f1c1f37a6fd6aa5d8bdee12c1b576d6728cf9751b8e61114286f08bb', 'llm_merchant': 'FS2307 Queensbury 73156', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'dd77874add7da58ef0d01fd1ca9ea2da5f684a13afdaf533d24760623c5d8419', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '84dfbb18d9df37fa9d80c93f575b9ed69b45821e15834b55be390bf7bcb35ca0', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'bcc42b4f037cf68aab9ef2ca5d8857edabcd59cb58aa5a74806a79556d012fe2', 'llm_merchant': 'O2', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '26cf81ab0b6763b45835180ec7fcf36a6fab1a87134a4e1d9f363981a85d5658', 'llm_merchant': 'THE GYM LTD', 'llm_category': 'health', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '9104568005ab2c9d81b96066745667a0a617bdcdd49c248aa77f5430d6700e08', 'llm_merchant': 'Jinal Patel', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'a0463b5ecba02e0b2f534b51a3a96435700091c40746862e82151cc3190f9787', 'llm_merchant': '071490 77608825 Withdrawal', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '160df8b9055811791bedb5416195539127fb99e585df443954261744b713ec7f', 'llm_merchant': 'Cards Direct Borehamwood GB', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '76fafdf286392b2260286914a0828c83421a557639531a1ed0e0401d786a496c', 'llm_merchant': "Pepe's Peri Peri London GB", 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '5b8ee163030ae3d41792aaf5f32f78177c99c46b6931bbcdf842a2054dc1e736', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE 0000000000000000', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '275d10b527c6e537b7accd7c93320feb9a3f8e3d125fcad060e55f795ac22633', 'llm_merchant': 'VEGGIE WOK LONDON GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'ebeb96a255f473f365236e772165180d76a223dacdcfdeadfa4594caae0d07f0', 'llm_merchant': 'TopCashback', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '5f6a209710f6d5558f84714f3719c94160d4a39e38ea5cddada0192274f41851', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE 0000000000000000', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '7f10e950d0703c3643141726c45f38cf52157552dbe452444572657b50a03d91', 'llm_merchant': 'Jaymin Patel', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '989f472d30b1cd443b33a386d42e2d8d786b40e50e1ce0d8169fde0581e65674', 'llm_merchant': '071490 77608825 Withdrawal', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'bdb22e0ae9511203db227cf3968c0aa7181899575ee2bc7bdd60f688c0da1d0b', 'llm_merchant': 'SOUTHERN FUNDING', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': '9ebf3cdfdad6e3cf0df5f397e6d88aa3b2f25e7f44ae3bc3cdea9ab597917131', 'llm_merchant': '071490 77608825 Withdrawal', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'd777813cd5101b6cda1f0d3a2fbbb312279253f11acbe433efd2917905078408', 'llm_merchant': '071986 03076275 Withdrawal', 'llm_category': 'other', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'b97d1cb6bd2b17bcf39ce36ea59edb7caf778363ada283b4f9ee903348152e51', 'llm_merchant': 'TAJ JAMIE R PATEL', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '2026-09-02T17:13:34.926444+00:00'}, {'event_id': 'f36b5adeb3940e47a4931101a2692b21b39ee77d4c16285b73a91047de865bda', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': True, 'updated_at': '202