In [1]:
from spending_tracker.database import supabase_client
from spending_tracker.database import transactions
from spending_tracker.data_ingestion import csv_parsing
from pathlib import Path

In [2]:
db_client = supabase_client.load_supabase_client()

In [3]:
processed_transactions_data_home = Path().resolve().parent / "data" / "transactions" / "processed"
transaction_metadata_home = Path().resolve().parent / "data" / "transactions_metadata"
print(processed_transactions_data_home)

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/processed

In [4]:
transactions_df = csv_parsing.load_csv_in_batch(processed_transactions_data_home,
                                                account_id=str)

transactions_metadata_df = csv_parsing.load_csv_in_batch(transaction_metadata_home)

In [5]:
transactions_df.head(10)

,event_id,date,month,account_id,user,bank,merchant,other_details,type,amount
0,4dfe72a057bb9e273208e3470ea91f0a64779283185e80...,2026-07-07,July-26,03076275,Joint,Nationwide,TAJ PATEL,NaN,NaN,500.00
1,897b964f7d4d2e001d6149f152bec20e3413e690eae85c...,2026-07-08,July-26,03076275,Joint,Nationwide,TESCO STORES 5620 LONDON GB,APPLEPAY 4914,NaN,-3.80
2,c70e40fe2579c0e27e76a1d16f8a7d91d3b5f4dd16b485...,2026-07-09,July-26,03076275,Joint,Nationwide,KAMLA PATEL,NaN,NaN,100.00
3,2f052381c3482ca02d6bd29a6ab5e1c764f2cae4414962...,2026-07-09,July-26,03076275,Joint,Nationwide,PRIYA CHAUHAN,NaN,NaN,190.00
4,f6a9bb8f21bc3aac5928d8395d55a38ec44b4ae25aa3d2...,2026-07-09,July-26,03076275,Joint,Nationwide,071490 77608825 Withdrawal 09 July 2026,NaN,NaN,-290.00
5,959b86f5d0ae066ddbefe59c6ba07d42e84f5bf2e7f678...,2026-07-10,July-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-9.36
6,2c25293fb239d900915db5245fc12bca371c76276e286d...,2026-07-11,July-26,03076275,Joint,Nationwide,ASDA SUPERSTORE COLINDALE GB,APPLEPAY 9160,NaN,-5.00
7,eae2b36adcf5123c180c574db84cd29b56170cbf07958c...,2026-07-11,July-26,03076275,Joint,Nationwide,FUNKY PIGEON BRISTOL GB,APPLEPAY 9160,NaN,-7.29
8,13d5d5ad99a408268ed354a262e3799425b332d0b54be2...,2026-07-11,July-26,03076275,Joint,Nationwide,MARKS&SPENCER PLC LONDON GB,APPLEPAY 9160,NaN,-7.43
9,c10b670b09fc44c817cbbe8359d89a61e87142dcf02045...,2026-07-11,July-26,03076275,Joint,Nationwide,M&S SALFORD INTERNET GB,APPLEPAY 5176,NaN,-25.00

In [6]:
transactions_metadata_df.head()

,event_id,llm_merchant,llm_category,manual_merchant,manual_category,manual_amount,hidden
0,4dfe72a057bb9e273208e3470ea91f0a64779283185e80...,TAJ PATEL,NaN,NaN,NaN,NaN,False
1,897b964f7d4d2e001d6149f152bec20e3413e690eae85c...,TESCO STORES 5620 LONDON GB,NaN,NaN,NaN,NaN,False
2,c70e40fe2579c0e27e76a1d16f8a7d91d3b5f4dd16b485...,KAMLA PATEL,NaN,NaN,NaN,NaN,False
3,2f052381c3482ca02d6bd29a6ab5e1c764f2cae4414962...,PRIYA CHAUHAN,NaN,NaN,NaN,NaN,False
4,f6a9bb8f21bc3aac5928d8395d55a38ec44b4ae25aa3d2...,071490 77608825 Withdrawal 09 July 2026,NaN,NaN,NaN,NaN,False

In [7]:
transactions_df.shape

(181, 10)

In [8]:
transactions_metadata_df.shape

(181, 7)

In [9]:
transactions.upload_transactions_to_db(transactions_df, 
                                       db_client, 
                                       table_name="transactions")

APIResponse(data=[{'event_id': '4dfe72a057bb9e273208e3470ea91f0a64779283185e80a84672c3607b9a5895', 'date': '2026-07-07', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TAJ PATEL', 'other_details': None, 'type': None, 'amount': 500, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '897b964f7d4d2e001d6149f152bec20e3413e690eae85c64cf552a453c7a11bc', 'date': '2026-07-08', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TESCO STORES 5620 LONDON GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -3.8, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'c70e40fe2579c0e27e76a1d16f8a7d91d3b5f4dd16b485cfd79d7614aa624131', 'date': '2026-07-09', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'KAMLA PATEL', 'other_details': None, 'type': None, 'amount': 100, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '2f052381c3482ca02d6bd29a6ab5e1c764f2cae441496204d9092b0a0a440843', 'date': '2026-07-09', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'PRIYA CHAUHAN', 'other_details': None, 'type': None, 'amount': 190, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'f6a9bb8f21bc3aac5928d8395d55a38ec44b4ae25aa3d2dbb814d4136ff8bbb5', 'date': '2026-07-09', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 09 July 2026', 'other_details': None, 'type': None, 'amount': -290, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '959b86f5d0ae066ddbefe59c6ba07d42e84f5bf2e7f678ff6a70bad9b96d4951', 'date': '2026-07-10', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -9.36, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '2c25293fb239d900915db5245fc12bca371c76276e286da3d1ff223ec1692af4', 'date': '2026-07-11', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'ASDA SUPERSTORE COLINDALE GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'eae2b36adcf5123c180c574db84cd29b56170cbf07958c51ab9274290c4bcd72', 'date': '2026-07-11', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'FUNKY PIGEON BRISTOL GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -7.29, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '13d5d5ad99a408268ed354a262e3799425b332d0b54be2e19c257657d4f574df', 'date': '2026-07-11', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MARKS&SPENCER PLC LONDON GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -7.43, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'c10b670b09fc44c817cbbe8359d89a61e87142dcf02045bca38c07c3b40e759f', 'date': '2026-07-11', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'M&S SALFORD INTERNET GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -25, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '68f2e9798110cbd9da1af002a6c39fdefb3e689d8ab8e1e0b8c0785a0905f62b', 'date': '2026-07-13', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Dunelm SoftFurnishings Leicester GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -30, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'faadf371a06329c1e894578f89ce0752590a2c67943c4911daca9d82c0008fa7', 'date': '2026-07-13', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Dunelm SoftFurnishings Leicester GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -30, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '53b976be9fb1ce840efd1921fc285ce6284390ae664e7c83956c0937f14bf279', 'date': '2026-07-15', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -10.75, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'f8552158d1ae5901ce5c317271c5ae9804f62116a17be404a8de689350548493', 'date': '2026-07-16', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MARKS&SPENCER PLC INTERNET GB', 'other_details': 'APPLEPAY 5176', 'type': None, 'amount': -25, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'a783fc67c49b577a1c1e4de9ed7e37bb82edfbbe934fd85fead89bc969e2bdbc', 'date': '2026-07-16', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'KAMLA PATEL', 'other_details': None, 'type': None, 'amount': 400, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '76f8cb86b44f2d89b0b6828296a81d77c8c00fb329621cca84e5f0602cdab1ac', 'date': '2026-07-17', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -8.35, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'ea187388ff0ed41e1b0b559ce694dde63bf38458a27fc5f4b28e905f3e18bd3b', 'date': '2026-07-18', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -6.57, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '75b0ed8fe677007da4772a667eec73135bf20fceeafde975d28455d93fa03f36', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 19 July 2026', 'other_details': None, 'type': None, 'amount': -400, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '570001ea22f91cd1d43315ba241b34d4a99bca525914dbd56f49aabec2f76173', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'VB & SONS HARROW GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -7.31, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '193fcadade1c0a5d051108fac37e771887eb32c9a61ce478b0b8009538a282b3', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'DOMINO S PIZZA MILTON KEYNES GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -15.76, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '4ca240894c1ed97d9418fea18db7a45479c83209fb431d2af7e705af9466ac07', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MARKS&SPENCER PLC LONDON GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -18.11, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '37944ce6756454fdef820a5f97bb5ba8745803a7abd29e34be9376bf0a87f470', 'date': '2026-07-21', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TAJ PATEL', 'other_details': None, 'type': None, 'amount': 1250, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '6f88c6700b31dc929f6c472fe80d86c06aa7d149cc8d81771cb50aeee16e0af2', 'date': '2026-07-21', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 21 July 2026', 'other_details': None, 'type': None, 'amount': -1250, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'd01ea4ace5f8abc5000c8c9800ab8b44f3a295f4e026cd6b2b571f3b6cb0f29a', 'date': '2026-07-21', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TESCO STORES 2126 BOREHAMWOOD GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -3.39, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'c99959e8154ef230a581cf62994d7d28f96c097383d1a2525a4d4a6d7d8ca6f6', 'date': '2026-07-21', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'ICELAND KINGSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -4.75, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '9e2c2e454baedfe437cfa909338db430336e16f83509df1a39f5ba54ec34e4ec', 'date': '2026-07-23', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -7.05, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '02817c2edddad641008aa6d06e839376c77dc3d69643b35b149a9689a8e02cac', 'date': '2026-07-24', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Dunelm SoftFurnishings Leicester GB 5176', 'other_details': None, 'type': None, 'amount': 30, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '2f48caabf5d212b722f6a72a34180c1ab47077e56d20450ac30d46a94fe35b20', 'date': '2026-07-24', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'LAHORE SPICE 3 LONDON GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -57.8, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '75d44cdb70a5bb8c5b411a8df427383f482550bc47ae4bea127d471e55901dd0', 'date': '2026-07-27', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'DOMINO S PIZZA MILTON KEYNES GB', 'other_details': 'APPLEPAY 4914', 'type': None, 'amount': -8.77, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '13e2f0fc7ec315da4ee1dc556af76ce1a03745646598d442cd8702bde42cd77d', 'date': '2026-07-27', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TESCO STORES 5620 LONDON GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -3.15, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'bd787daa08c82058648318756f0be7783c385373247b53f1f4a9673a25402b77', 'date': '2026-07-29', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Credit 29 July 2026', 'other_details': None, 'type': None, 'amount': 10265, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'b92bab2739fc44f7009cccfc095eba29019f14d568539a92f8189e55bba4b05b', 'date': '2026-07-29', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'Credit 29 July 2026', 'other_details': None, 'type': None, 'amount': 651, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'f335ef120e26ad9a5eefa696dc11a9df6fea10fad9cfa6df42b61fae80dc1e84', 'date': '2026-07-29', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'TAJ PATEL', 'other_details': None, 'type': None, 'amount': 100, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '62da1e0abb6245225934e33561fac415cb613ad4b3ef8b12971a1926af7d099f', 'date': '2026-07-29', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 29 July 2026', 'other_details': None, 'type': None, 'amount': -10365, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '71b5b3b521bce07877f354398045221274ed0b1a953daddca7ea219bb14b5c18', 'date': '2026-07-31', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 31 July 2026', 'other_details': None, 'type': None, 'amount': -651, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'ac37a354329825bea1c13ad119af71cee0aa1da657df1220498816722e0e9852', 'date': '2026-07-31', 'month': 'July-26', 'account_id': '03076275', 'user': 'Joint', 'bank': 'Nationwide', 'merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'other_details': 'APPLEPAY 9160', 'type': None, 'amount': -4.8, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '1250520dee7b2ebf2b2de5a853dcb675c7fae27002bf87c6ef0765566813ccc7', 'date': '2026-07-28', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'WM MORRISONS STORES - Q', 'other_details': 'LONDON', 'type': None, 'amount': -6.5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'a7a47f104cc12aa1e396154fc9c549a1daa25529236f2af80030f1a5163c111d', 'date': '2026-07-23', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'WM MORRISONS STORES - Q', 'other_details': 'LONDON', 'type': None, 'amount': -3.5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '72a27fac5109a6f45a5a75c01a085ddebbaca39b0530e1fe4bde6611f3299412', 'date': '2026-07-22', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'FS2307 Queensbury 73156', 'other_details': 'Stanmore', 'type': None, 'amount': -60, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '6d9e7057569a93dabe6dc513d424eb0b374407b29f94c234dd20b70217c9bc13', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TESCO STORE 2126 2126TE', 'other_details': 'BOREHAMWOOD', 'type': None, 'amount': -4.5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'e8ff32ca9b78bc7f629c82b6132902143ab3085a9ac6283ba1cbf4eb319141f3', 'date': '2026-07-18', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'AMAZON.CO.UK*5Q00B9ZR5', 'other_details': 'AMAZON.CO.UK', 'type': None, 'amount': -39.42, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'a28686276e50e0ba6077557bbb4b15fcfcc273a8190cd7222ebb0379a55bd90e', 'date': '2026-07-18', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'ASDA STORES', 'other_details': 'LONDON', 'type': None, 'amount': -11, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'ea3edcd77678cf05ea790b3e28054ea2d9809c4ce923c165283608cabce32214', 'date': '2026-07-14', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'TESCO STORE 2126 2126TE', 'other_details': 'BOREHAMWOOD', 'type': None, 'amount': -8, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '9695cc15562e0dcff877216ef66f515a6e32e87c0706eaad1b63f9222bfb6203', 'date': '2026-07-13', 'month': 'July-26', 'account_id': '51016', 'user': 'Radhika', 'bank': 'Amex', 'merchant': 'AMZNMKTPLACE*SC2GE5OF5', 'other_details': 'AMAZON.CO.UK', 'type': None, 'amount': -18.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '78c1c95efb7c1bed3bf124366def8021bf06a712cb7ae86b2f9d185b9530b55e', 'date': '2026-07-01', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'APPLE.COM/BILL 08001076285 IE', 'other_details': None, 'type': None, 'amount': -6.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '2eccd9eedff35c22373339fbfab3d07afa07e98b38ee05012f866190309c0c2f', 'date': '2026-07-03', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'O2', 'other_details': None, 'type': None, 'amount': -10.5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'a667376420e2eb6980888eef07561d4b9f114158eebe5dbeb7462f07a856f72f', 'date': '2026-07-03', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'THE GYM LTD', 'other_details': None, 'type': None, 'amount': -18.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '584b0b17188f0bf08af316ad8448ccc1be328113c01a795f530adf1a13ae3d05', 'date': '2026-07-07', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'TAJ JAMIE R PATEL', 'other_details': None, 'type': None, 'amount': -571, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '4012a9881397032a8792f72c8d94280af1d80dc7cc3e53f26cbcc93d988715c2', 'date': '2026-07-07', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'RADHIKA PATEL', 'other_details': None, 'type': None, 'amount': -2000, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '80d245c7acb6fee362118b264486547e5a82ee331a0ff78ae2539955759c06ed', 'date': '2026-07-07', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'RADHIKA PATEL', 'other_details': None, 'type': None, 'amount': -1200, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'c74d97862d16e2dd6aceee7ac06a66ac22a709faa202042ffc2ecce39af43e94', 'date': '2026-07-08', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'TAJ PATEL', 'other_details': None, 'type': None, 'amount': 235, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '21e6a0242e89384ca2bc33b7b1c9d90e7db09082ea414b7fb3b9ffc8c668ed35', 'date': '2026-07-09', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 09 July 2026', 'other_details': None, 'type': None, 'amount': -300, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'f38aac407a13b4ff44137344291f07ba56bcd4698b6fc6376dce4639cebcf80a', 'date': '2026-07-16', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'AMAZON* JC35T2MU5 LONDON GB 0253', 'other_details': None, 'type': None, 'amount': -3.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': 'ef05cc0824dd8c80aa4d4460afa097ec709710884194c4c7f6c9f6a89db22cf5', 'date': '2026-07-16', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'AMAZON* 1H5IT6V05 LONDON GB 0253', 'other_details': None, 'type': None, 'amount': -16.98, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '9e70088e6419c2c84bfbd46fd374398800fabcf4a76dc0534485ae192feabcac', 'date': '2026-07-17', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'SAVERS HEALTH & BEAUTY BOREHAMWOOD GB', 'other_details': 'APPLEPAY 6855', 'type': None, 'amount': -2.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '42d26ee145f7b7134dac391966e3980a301e89fc8645006d7ca5db9bfc773636', 'date': '2026-07-17', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'BOOTS, BOREHAMWOOD BOREHAMWOOD GB', 'other_details': 'APPLEPAY 6855', 'type': None, 'amount': -3.5, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '466fd15b36eea772a052ed22937fee59d64fba4b3e0515c8056031dffad0cfa7', 'date': '2026-07-17', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'Wellington Borehamwood GB', 'other_details': 'APPLEPAY 6855', 'type': None, 'amount': -10.95, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '219267c7008fef3ff125df21b1322eb497e84341f14f115db26f7e07be059b88', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': 'APPLE.COM/BILL CORK IE', 'other_details': None, 'type': None, 'amount': -8.99, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '2ad8686d2ac069f829320f19976d96f3e20b85905c31698b03384de7a0e6b777', 'date': '2026-07-20', 'month': 'July-26', 'account_id': '34490057', 'user': 'Radhika', 'bank': 'Nationwide', 'merchant': '071490 77608825 Withdrawal 19 July 2026', 'other_details': None, 'type': None, 'amount': -251, 'updated_at': '2026-08-26T15:26:50.48158+00:00'}, {'event_id': '

In [11]:
transactions.upload_transactions_to_db(transactions_metadata_df, 
                                       db_client, 
                                       table_name="transactions_metadata", 
                                       exclude_columns=["manual_merchant", "manual_category", "manual_amount", "hidden"])

APIResponse(data=[{'event_id': '4dfe72a057bb9e273208e3470ea91f0a64779283185e80a84672c3607b9a5895', 'llm_merchant': 'TAJ PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '897b964f7d4d2e001d6149f152bec20e3413e690eae85c64cf552a453c7a11bc', 'llm_merchant': 'TESCO STORES 5620 LONDON GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'c70e40fe2579c0e27e76a1d16f8a7d91d3b5f4dd16b485cfd79d7614aa624131', 'llm_merchant': 'KAMLA PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '2f052381c3482ca02d6bd29a6ab5e1c764f2cae441496204d9092b0a0a440843', 'llm_merchant': 'PRIYA CHAUHAN', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'f6a9bb8f21bc3aac5928d8395d55a38ec44b4ae25aa3d2dbb814d4136ff8bbb5', 'llm_merchant': '071490 77608825 Withdrawal 09 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '959b86f5d0ae066ddbefe59c6ba07d42e84f5bf2e7f678ff6a70bad9b96d4951', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '2c25293fb239d900915db5245fc12bca371c76276e286da3d1ff223ec1692af4', 'llm_merchant': 'ASDA SUPERSTORE COLINDALE GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'eae2b36adcf5123c180c574db84cd29b56170cbf07958c51ab9274290c4bcd72', 'llm_merchant': 'FUNKY PIGEON BRISTOL GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '13d5d5ad99a408268ed354a262e3799425b332d0b54be2e19c257657d4f574df', 'llm_merchant': 'MARKS&SPENCER PLC LONDON GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'c10b670b09fc44c817cbbe8359d89a61e87142dcf02045bca38c07c3b40e759f', 'llm_merchant': 'M&S SALFORD INTERNET GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '68f2e9798110cbd9da1af002a6c39fdefb3e689d8ab8e1e0b8c0785a0905f62b', 'llm_merchant': 'Dunelm SoftFurnishings Leicester GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'faadf371a06329c1e894578f89ce0752590a2c67943c4911daca9d82c0008fa7', 'llm_merchant': 'Dunelm SoftFurnishings Leicester GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '53b976be9fb1ce840efd1921fc285ce6284390ae664e7c83956c0937f14bf279', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'f8552158d1ae5901ce5c317271c5ae9804f62116a17be404a8de689350548493', 'llm_merchant': 'MARKS&SPENCER PLC INTERNET GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'a783fc67c49b577a1c1e4de9ed7e37bb82edfbbe934fd85fead89bc969e2bdbc', 'llm_merchant': 'KAMLA PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '76f8cb86b44f2d89b0b6828296a81d77c8c00fb329621cca84e5f0602cdab1ac', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'ea187388ff0ed41e1b0b559ce694dde63bf38458a27fc5f4b28e905f3e18bd3b', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '75b0ed8fe677007da4772a667eec73135bf20fceeafde975d28455d93fa03f36', 'llm_merchant': '071490 77608825 Withdrawal 19 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '570001ea22f91cd1d43315ba241b34d4a99bca525914dbd56f49aabec2f76173', 'llm_merchant': 'VB & SONS HARROW GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '193fcadade1c0a5d051108fac37e771887eb32c9a61ce478b0b8009538a282b3', 'llm_merchant': 'DOMINO S PIZZA MILTON KEYNES GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '4ca240894c1ed97d9418fea18db7a45479c83209fb431d2af7e705af9466ac07', 'llm_merchant': 'MARKS&SPENCER PLC LONDON GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '37944ce6756454fdef820a5f97bb5ba8745803a7abd29e34be9376bf0a87f470', 'llm_merchant': 'TAJ PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '6f88c6700b31dc929f6c472fe80d86c06aa7d149cc8d81771cb50aeee16e0af2', 'llm_merchant': '071490 77608825 Withdrawal 21 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'd01ea4ace5f8abc5000c8c9800ab8b44f3a295f4e026cd6b2b571f3b6cb0f29a', 'llm_merchant': 'TESCO STORES 2126 BOREHAMWOOD GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'c99959e8154ef230a581cf62994d7d28f96c097383d1a2525a4d4a6d7d8ca6f6', 'llm_merchant': 'ICELAND KINGSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '9e2c2e454baedfe437cfa909338db430336e16f83509df1a39f5ba54ec34e4ec', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '02817c2edddad641008aa6d06e839376c77dc3d69643b35b149a9689a8e02cac', 'llm_merchant': 'Dunelm SoftFurnishings Leicester GB 5176', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '2f48caabf5d212b722f6a72a34180c1ab47077e56d20450ac30d46a94fe35b20', 'llm_merchant': 'LAHORE SPICE 3 LONDON GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '75d44cdb70a5bb8c5b411a8df427383f482550bc47ae4bea127d471e55901dd0', 'llm_merchant': 'DOMINO S PIZZA MILTON KEYNES GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '13e2f0fc7ec315da4ee1dc556af76ce1a03745646598d442cd8702bde42cd77d', 'llm_merchant': 'TESCO STORES 5620 LONDON GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'bd787daa08c82058648318756f0be7783c385373247b53f1f4a9673a25402b77', 'llm_merchant': 'Credit 29 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'b92bab2739fc44f7009cccfc095eba29019f14d568539a92f8189e55bba4b05b', 'llm_merchant': 'Credit 29 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'f335ef120e26ad9a5eefa696dc11a9df6fea10fad9cfa6df42b61fae80dc1e84', 'llm_merchant': 'TAJ PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '62da1e0abb6245225934e33561fac415cb613ad4b3ef8b12971a1926af7d099f', 'llm_merchant': '071490 77608825 Withdrawal 29 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '71b5b3b521bce07877f354398045221274ed0b1a953daddca7ea219bb14b5c18', 'llm_merchant': '071490 77608825 Withdrawal 31 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'ac37a354329825bea1c13ad119af71cee0aa1da657df1220498816722e0e9852', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '1250520dee7b2ebf2b2de5a853dcb675c7fae27002bf87c6ef0765566813ccc7', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'a7a47f104cc12aa1e396154fc9c549a1daa25529236f2af80030f1a5163c111d', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '72a27fac5109a6f45a5a75c01a085ddebbaca39b0530e1fe4bde6611f3299412', 'llm_merchant': 'FS2307 Queensbury 73156', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '6d9e7057569a93dabe6dc513d424eb0b374407b29f94c234dd20b70217c9bc13', 'llm_merchant': 'TESCO STORE 2126 2126TE', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'e8ff32ca9b78bc7f629c82b6132902143ab3085a9ac6283ba1cbf4eb319141f3', 'llm_merchant': 'AMAZON.CO.UK*5Q00B9ZR5', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'a28686276e50e0ba6077557bbb4b15fcfcc273a8190cd7222ebb0379a55bd90e', 'llm_merchant': 'ASDA STORES', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'ea3edcd77678cf05ea790b3e28054ea2d9809c4ce923c165283608cabce32214', 'llm_merchant': 'TESCO STORE 2126 2126TE', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '9695cc15562e0dcff877216ef66f515a6e32e87c0706eaad1b63f9222bfb6203', 'llm_merchant': 'AMZNMKTPLACE*SC2GE5OF5', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '78c1c95efb7c1bed3bf124366def8021bf06a712cb7ae86b2f9d185b9530b55e', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '2eccd9eedff35c22373339fbfab3d07afa07e98b38ee05012f866190309c0c2f', 'llm_merchant': 'O2', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'a667376420e2eb6980888eef07561d4b9f114158eebe5dbeb7462f07a856f72f', 'llm_merchant': 'THE GYM LTD', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '584b0b17188f0bf08af316ad8448ccc1be328113c01a795f530adf1a13ae3d05', 'llm_merchant': 'TAJ JAMIE R PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '4012a9881397032a8792f72c8d94280af1d80dc7cc3e53f26cbcc93d988715c2', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '80d245c7acb6fee362118b264486547e5a82ee331a0ff78ae2539955759c06ed', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'c74d97862d16e2dd6aceee7ac06a66ac22a709faa202042ffc2ecce39af43e94', 'llm_merchant': 'TAJ PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '21e6a0242e89384ca2bc33b7b1c9d90e7db09082ea414b7fb3b9ffc8c668ed35', 'llm_merchant': '071490 77608825 Withdrawal 09 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'f38aac407a13b4ff44137344291f07ba56bcd4698b6fc6376dce4639cebcf80a', 'llm_merchant': 'AMAZON* JC35T2MU5 LONDON GB 0253', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'ef05cc0824dd8c80aa4d4460afa097ec709710884194c4c7f6c9f6a89db22cf5', 'llm_merchant': 'AMAZON* 1H5IT6V05 LONDON GB 0253', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '9e70088e6419c2c84bfbd46fd374398800fabcf4a76dc0534485ae192feabcac', 'llm_merchant': 'SAVERS HEALTH & BEAUTY BOREHAMWOOD GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '42d26ee145f7b7134dac391966e3980a301e89fc8645006d7ca5db9bfc773636', 'llm_merchant': 'BOOTS, BOREHAMWOOD BOREHAMWOOD GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '466fd15b36eea772a052ed22937fee59d64fba4b3e0515c8056031dffad0cfa7', 'llm_merchant': 'Wellington Borehamwood GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '219267c7008fef3ff125df21b1322eb497e84341f14f115db26f7e07be059b88', 'llm_merchant': 'APPLE.COM/BILL CORK IE', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '2ad8686d2ac069f829320f19976d96f3e20b85905c31698b03384de7a0e6b777', 'llm_merchant': '071490 77608825 Withdrawal 19 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '1ce687e268619548aebaa86c58233af705db767e663de60032f7c22a8856b359', 'llm_merchant': 'NORTH MYMMS PARK LTD', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'a2943df8c3657e9723551328c721d327768908f5b77b2e567ba473fca259f79c', 'llm_merchant': '071490 77608825 Withdrawal 24 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '5a68a62a5a12872df6146ac9cd5d296e49f633b8be5c554730545c2e1d0b3960', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'e2421ed4459037aef97cf323985b10f190d1f287c66c6d288046f0ec34d9590e', 'llm_merchant': 'SOUTHERN FUNDING', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '635edb75f8c7e2e001951c9b3d29fc300b4fe5c86a66c0e1dad44be37bad7806', 'llm_merchant': '071490 77608825 Withdrawal 28 July 2026', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '483c3553cd1efbf8cd710eadba5555f657e22cec2d6a2a2d55d5208c68dc71fa', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'b2d973207e21ad8e283f88d5a087ebeb6ca448f09e264cffef77b4d0d8447d0b', 'llm_merchant': 'PAYPAL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '8acc39d093237ce3ba87f560a50b722bb2805205647f889a5b58946525b0f008', 'llm_merchant': 'TAJ JAMIE R PATEL', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '9a632f748c6696c8f51e30e06e3932682bbb675a7a0ec1f0485b3a990c01c8d0', 'llm_merchant': 'Amazon.co.uk*4M1E53C05 AMAZON.CO.UK GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': '60e30d4fb44a15b5e68c7fc1121ed525be98a0ed95d21e640443789490996436', 'llm_merchant': 'Cards Direct Borehamwood GB', 'llm_category': None, 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-08-26T15:26:59.667221+00:00'}, {'event_id': 'aedf6d7e3c48b009d422638b47f3c4e9aaa9efb1466a90a